### ISSUE TITLE
Is it possible to run Leffa with just the CPU?

### ISSUE THREAD

**Issue by EdsMElo** [franciszzj/Leffa#18]
I tried to run it using pytorch CPU and got the following message:

(leffa) root@dominiologico:/opt/projects/Leffa# python app.py
Fetching 37 files: 100%|████████████████████████████| 37/37 [00:00<00:00, 974.92it/s]
Traceback (most recent call last):
  File "/opt/projects/Leffa/app.py", line 146, in <module>
    leffa_predictor = LeffaPredictor()
  File "/opt/projects/Leffa/app.py", line 21, in __init__
    self.mask_predictor = AutoMasker(
  File "/opt/projects/Leffa/leffa_utils/garment_agnostic_mask_predictor.py", line 211, in __init__
    self.densepose_processor = DensePose(densepose_path, device)
  File "/opt/projects/Leffa/leffa_utils/densepose_for_mask.py", line 40, in __init__
    self.predictor = DefaultPredictor(self.cfg)
  File "/opt/projects/Leffa/detectron2/engine/defaults.py", line 282, in __init__
    self.model = build_model(self.cfg)
  File "/opt/projects/Leffa/detectron2/modeling/meta_arch/build.py", line 23, in build_model
    model.to(torch.device(cfg.MODEL.DEVICE))
  File "/root/miniconda3/envs/leffa/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1340, in to
    return self._apply(convert)
  File "/root/miniconda3/envs/leffa/lib/python3.10/site-packages/torch/nn/modules/module.py", line 900, in _apply
    module._apply(fn)
  File "/root/miniconda3/envs/leffa/lib/python3.10/site-packages/torch/nn/modules/module.py", line 900, in _apply
    module._apply(fn)
  File "/root/miniconda3/envs/leffa/lib/python3.10/site-packages/torch/nn/modules/module.py", line 927, in _apply
    param_applied = fn(param)
  File "/root/miniconda3/envs/leffa/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1326, in convert
    return t.to(
  File "/root/miniconda3/envs/leffa/lib/python3.10/site-packages/torch/cuda/__init__.py", line 310, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by franciszzj** [comment]
It is feasible, but it requires modifying the code to ensure all operations that are currently set to run on the GPU are changed to run on the CPU instead. This allows computation to be performed on the CPU (though it will naturally be much slower).
This should be relatively easy to implement locally.
