### ISSUE TITLE
ModuleNotFoundError: No module named 'SCHP'

### ISSUE THREAD

**Issue by gavincoder-china** [franciszzj/Leffa#20]
(Leffa) PS D:\Leffa-try> python app.py       
Traceback (most recent call last):
  File "D:\Leffa-try\app.py", line 7, in <module>
    from leffa_utils.garment_agnostic_mask_predictor import AutoMasker
  File "D:\Leffa-try\leffa_utils\garment_agnostic_mask_predictor.py", line 9, in <module>
    from SCHP import SCHP  # type: ignore
ModuleNotFoundError: No module named 'SCHP'

I tried so many methods, but did not solve this problem, Do you have any suggestion?

**Comment by NielHung** [comment]
windows下问题比较多，你可以试下wsl
