### ISSUE TITLE
how to install SCHP, detectron and densepose

### ISSUE THREAD

**Issue by TanvirHafiz** [franciszzj/Leffa#25]
where to place the thirdparty requirements inside of leffa?

**Comment by franciszzj** [comment]
When cloning this project, all of these will be automatically downloaded, with no additional installation required.

**Comment by TanvirHafiz** [comment]
(venv) F:\Leffa>python app.py
Traceback (most recent call last):
  File "F:\Leffa\app.py", line 7, in <module>
    from leffa_utils.garment_agnostic_mask_predictor import AutoMasker
  File "F:\Leffa\leffa_utils\garment_agnostic_mask_predictor.py", line 9, in <module>
    from SCHP import SCHP  # type: ignore
ModuleNotFoundError: No module named 'SCHP' aparently it did not. updates the repo just now and fresh installed requirements

**Comment by rodney-greenfield-akqa** [comment]
Try ...

```
(leffa) PS F:\Leffa> ren SCHP SCHP_config.txt
(leffa) PS F:\Leffa> $env:PYTHONPATH = "F:\Leffa\3rdparty"
(leffa) PS F:\Leffa> python app.py
```
